xz(1): Remove the unneeded '${LZMADIR}/api/lzma' search path
This search path is unneeded, as the API headers there must be included
via the public header '${LZMADIR}/api/lzma.h'.

In addition, it would cause conflict with other headers in
liblzma/{check,common} etc. directories.  This happened when I tried
to adjust the per-group flags to override the default flags (e.g.,
CFLAGS).  An example error log is:

```
In file included from /usr/src/usr.bin/xz/../../contrib/xz/src/liblzma/common/block_buffer_encoder.c:17:
/usr/src/usr.bin/xz/../../contrib/xz/src/liblzma/api/lzma/check.h:16:3: error: #error Never include this file directly. Use <lzma.h> instead.
 # error Never include this file directly. Use <lzma.h> instead.
   ^~~~~
```